#!/bin/sh
# DAY-SE : Swedish Theme Days (+some international joke-y days. in swedish) (excl. holidays & days with moving dates). Use as-is (or as variable for other programs) - Kjell Emanuelsson 2024
day="d"$(date +%m%d)
declare -A days
days=(
["d0101"]="Internationella pizzadagen"
["d0102"]="Världsdagen för introverta"
["d0103"]="Internationella JRR Tolkien-dagen"
["d0104"]="Punktskriftens dag
Världshypnosdagen"
["d0107"]="Temadagens dag"
["d0112"]="Marsipanens dag"
["d0115"]="Tulpanens dag"
["d0116"]="Internationella LCHF-dagen"
["d0117"]="Internationella fetischdagen"
["d0118"]="Internationella Nalle Puh-dagen"
["d0119"]="Sten Stures ben
Internationella popcorndagen"
["d0121"]="Kramens dag "
["d0122"]="Vinets dag
Pilsnerfilmens dag"
["d0123"]="Elens dag"
["d0124"]="Frufridagen"
["d0125"]="Halvsnödagen"
["d0126"]=""
["d0127"]="Hemtjänstens dag"
["d0128"]="Dataskyddsdagen
Konungens namnsdag
Internationella LEGO-dagen"
["d0129"]="Veganpizza-dagen"
["d0131"]="Pandemidagen
Lönekonsultens dag
Upp och hoppa-dagen"
["d0201"]="Vegetariska dagen"
["d0202"]="Murmeldjursdagen
Internationella tvillingdagen
Smoothiens dag"
["d0203"]="Andningens dag
Morotskakans dag"
["d0204"]="Världscancerdagen
Vargens dag"
["d0205"]="Nutelladagen
Runebergsdagen"
["d0206"]="Samernas nationaldag
Semikolonets dag"
["d0207"]="Tankens dag
Trafiklärarens dag"
["d0208"]="Äggahalvans dag"
["d0211"]="Internationella 112-dagen
Världsdagen för de sjuka"
["d0212"]="Darwins födelsedag
Djurförsökens dag"
["d0213"]="Tandborstbytardagen"
["d0214"]="Alla hjärtans dag
Alla hjärtebarns dag"
["d0215"]="Internationella barncancerdagen
Geléhallonens dag"
["d0218"]="Fotens dag"
["d0219"]="Knäckebrödets dag"
["d0220"]="Slarvighetens dag
Internationella piprökardagen"
["d0221"]="Fondvalsdagen"
["d0222"]="Alla scouters dag*
Internationella brottsofferdagen"
["d0223"]="Kakelplattans dag"
["d0224"]="Sverigefinnarnas dag
Internationella EBM-dagen"
["d0225"]="Grapefruktens dag"
["d0227"]="Internationella isbjörnsdagen "
["d0228"]="Internationella musarmsdagen
Myggholkens dag
Kalevaladagen"
["d0301"]="Krama en bibliotekarie-dagen"
["d0302"]="Serietidningens dag"
["d0303"]="Dagen för musikalisk frihet
Mandelkubbens dag"
["d0304"]="Bananens dag"
["d0305"]="Ostbågens dag"
["d0306"]="Europeiska logopeddagen"
["d0307"]="Punschrullens dag
Podcastens dag"
["d0309"]="Tomatsåsens dag"
["d0310"]="V8-motorns dag
Super Mario-dagen"
["d0311"]="Europeisk minnesdag för terrorismens offer
Rörmokeriets världsdag"
["d0312"]="Världsdagen mot cybercensur
Världsglaukomdagen
Republiken Jamtland
Alla korvars dag
Nationella syntolkningsdagen
Kronprinsessans namnsdag"
["d0313"]="Mazarindagen
Källkritikens dag"
["d0314"]="Pi-dagen
Steak and BJ day
Matematikens dag"
["d0315"]="Internationella dagen mot polisvåld
Internationella konsumentdagen
NPF-dagen"
["d0316"]="Stoppa incestdagen
Kvänfolkets dag"
["d0317"]="Kollektivavtalets dag
Hallongrottans dag"
["d0318"]="Bussförarens dag
Internationella barnreumatikerdagen"
["d0319"]="Supporterns dag"
["d0320"]="Internationella munhälsodagen
Världsberättardagen
Internationella glädjedagen
World Salad Day"
["d0321"]="Internationella dockteaterdagen
Internationella färgdagen
Rocka sockorna-dagen
Internationella skogsdagen"
["d0322"]="Kennethdagen"
["d0323"]="Nordens dag
Matlådans dag"
["d0324"]="Europeiska dagen för hantverksmässigt tillverkad glass"
["d0325"]="Trandagen
Våffeldagen
Tolkien reading day"
["d0326"]="Dialersystemens dag
Arbetsplatsombudens dag"
["d0327"]="Världsteaterdagen"
["d0330"]="Bipolärdagen"
["d0331"]="Världsbackupdagen
Int. dagen för synliggörande av transpersoner
Kullerbyttans dag"
["d0401"]="Skojardagen"
["d0402"]="Internationella barnboksdagen
Studenternas dag"
["d0403"]="Kärlekens dag"
["d0404"]="Morotens dag"
["d0405"]="Capsens dag"
["d0406"]="Barn på sjukhusdagen
Pingisens dag
Internationella Carbonara dagen"
["d0408"]="Romernas internationella dag"
["d0409"]="CSS-naked day"
["d0410"]="Bulle med bullens-dag
Internationella syskondagen"
["d0411"]="Internationella parkinsondagen"
["d0412"]="Lakritsdagen
Surdegsdagen
Linssoppans dag"
["d0413"]="Knytblusens dag"
["d0414"]="Volvons dag
Cake and Cunnilingus Day"
["d0415"]="Internationella biomedicinska analytikerdagen"
["d0416"]="Världsröstdagen"
["d0417"]="De blödarsjukas dag
Folkhögskolans dag"
["d0418"]="Amatörradions dag"
["d0419"]="Skottkärrans dag"
["d0420"]="Internationella cannabisdagen
Polkagrisens dag
Svenska gin & tonic-dagen"
["d0421"]="Terrakottakrukans dag"
["d0423"]="Världsbokdagen"
["d0424"]="Försöksdjurens dag"
["d0425"]="Världsmalariadagen
Mamatummy Day
Lekens dag"
["d0426"]="Promenadens dag
Alien-dagen"
["d0427"]="Världstapirdagen"
["d0428"]="Möteskulturdagen"
["d0429"]="Dansens dag
Svenska friluftsdagen"
["d0430"]="Valborgsmässoafton
Konungens födelsedag"
["d0501"]="Första maj / Arbetarrörelsens dag
Budapestbakelsens dag"
["d0502"]="Harry potter-dagen
Världsdagen för tonfisk"
["d0503"]="Asociala dagen"
["d0504"]="Fothälsodagen
Star wars-dagen"
["d0505"]="Internationella barnmorskedagen
Internationella kebabdagen
Internationella handhygiendagen
Internationella Ragdolldagen"
["d0506"]="Inkontinensdagen
Dragspelets dag
Hembakatdagen
Regnbågsfamiljers dag"
["d0508"]="Internationella vikingadagen
Röda Korsets dag"
["d0509"]="Europadagen
Nedkopplingens dag
Linderödsgrisens dag"
["d0510"]="Internationella SLE-dagen"
["d0511"]="Chokladbollens dag
Nämndemännens dag"
["d0512"]="Internationella fibromyalgidagen
Internationella sjuksköterskedagen
Massagens dag
ME/CFS-dagen
Dagbokens dag
Snellmansdagen"
["d0513"]="Receptionistens dag"
["d0514"]="Svenska teckenspråkets dag
Rumpans dag"
["d0515"]="Kardemummabullens dag
Arbetslöshetens dag"
["d0516"]="Internationella celiakidagen"
["d0517"]="Internationella dagen mot homo- och transfobi"
["d0518"]="Fascinerande växters dag
Internationella museidagen"
["d0519"]="Nationella mag-och tarmdagen
Halloumiostens dag"
["d0520"]="Williams syndromdagen
Kulturskolans dag"
["d0522"]="Picknickens dag"
["d0523"]="Internationella sköldpaddsdagen
Måltidens gemenskapsdag"
["d0524"]="Nationalparkernas dag
Ofrivilligt barnlösas dag
Religionstraumadagen"
["d0525"]="Internationella nörddagen
Handduksdagen
Internationella sköldkörteldagen"
["d0526"]="Muffinsdagen
Ostens dag"
["d0528"]="Den stressfria dagen
Internationella krama en musiker-dagen
Internationella burgardagen
Internationella mensdagen"
["d0529"]="Veterandagen"
["d0530"]="Internationella MS-dagen
Fönsterrenoveringens dag"
["d0601"]="Mjölkens dag
Mobilfria dagen"
["d0602"]="Internationella artrosdagen
Internationella dagen mot ätstörningar"
["d0603"]="Internationella klumpfotsdagen"
["d0604"]="Assistansens dag"
["d0605"]="Alla vänners dag
Barfotadagen"
["d0606"]="Dagen-D
Fruktens dag
Färskpotatisens dag
Sillens dag
Sveriges nationaldag
Internationella donutdagen
Den stora lupinbekämpardagen
Motorhistoriska dagen"
["d0607"]="Punkens dag"
["d0609"]="Internationella arkivdagen
Brickbandens dag"
["d0615"]="Chaufförens dag"
["d0616"]="Bloomsday
Redovisningskonsultens dag"
["d0618"]="Internationella picknickdagen
Pionens dag
Internationella sushidagen
Internationella dagen för hållbar gastronomi"
["d0619"]="Internationella flanerardagen
Frisörens dag"
["d0620"]="Internationella surfdagen"
["d0621"]="Internationella ALS-dagen
Långsamhetens dag
Världsmusikdagen
Internationella yogadagen
Giraffens dag
Internationella selfiedagen
Världshumanistdagen"
["d0622"]="Internationella dagen för änkor"
["d0626"]="Chokladpuddingens dag"
["d0630"]="Pilsnerkorvens dag
Internationella dagen för asteroider"
["d0701"]="Silikonbröstens dag"
["d0702"]="Rosens dag"
["d0706"]="Internationella kyssdagen"
["d0707"]="Hudvårdens dag"
["d0710"]="Hoya - Porslinsblommans dag"
["d0711"]="Internationella råkostdagen
Internationella minnesdagen för Srebrenica"
["d0712"]="Fulhetens dag"
["d0713"]="Paltdagen
Internationella rock and roll-dagen"
["d0714"]="Kronprinsessans födelsedag
Internationella dagen för ickebinära"
["d0715"]="Tornedalingarnas dag"
["d0717"]="Dagen för världsomfattande rättvisa
Emojins dag"
["d0720"]="Internationella schackdagen"
["d0722"]="Approximativa pi-dagen"
["d0723"]="Varmkorvens dag"
["d0724"]="Internationella BDSM-dagen
Drive-thru dagen"
["d0725"]="Trä nålen-dagen"
["d0726"]="Bellmandagen
Esperantodagen"
["d0727"]="Sjusovardagen
Gå på styltor-dagen"
["d0728"]="Jakttornets dag"
["d0729"]="Internationella tigerdagen
Lasagnens dag"
["d0730"]="Världsbroderidagen
Pocketbokens dag"
["d0731"]="Världsvänskapsdagen
Dagen för ovanliga instrument"
["d0801"]="Alla flickvänners dag"
["d0803"]="Vattenmelonens dag"
["d0804"]="Alla systrars dag"
["d0806"]="Hiroshimadagen
Internationella dagen för frisk andedräkt"
["d0808"]="Internationella orgasmdagen
Kräftpremiären
Lyckans dag
Internationella kattdagen
Drottningens namnsdag"
["d0809"]="Rulltårtans dag
Mumindagen"
["d0810"]="Lejonets dag"
["d0813"]="Vänsterhäntas dag"
["d0815"]="Mormorsrutans dag"
["d0816"]="Berätta ett skämt-dagen"
["d0819"]="Luftfartsdagen"
["d0820"]="Honungens dag"
["d0821"]="Världsentreprenörsdagen
Alla pensionärers dag
Durspelets dag
Groggens dag"
["d0822"]="Internationella müslidagen"
["d0823"]="Köttbullens dag"
["d0824"]="Årsdagen av Plutos degradering
Bartolomeidagen
Tandvårdsrädslans dag"
["d0826"]="Alla hundars dag
Jämställdhetsdagen"
["d0827"]="Sveriges Raoul Wallenbergdag"
["d0828"]="World day of Turner Syndrome"
["d0831"]="Internationella förebildsdagen"
["d0901"]="Fluortantens dag
Däckcheckdagen"
["d0902"]="Nationella tapetserardagen"
["d0903"]="Skolledarnas dag"
["d0904"]="Dagen för ungas psykiska hälsa"
["d0905"]="Internationella dagen för välgörenhet"
["d0907"]="Salamins dag
Stora duchennesdagen"
["d0908"]="Internationella fysioterapins dag"
["d0909"]="Yrkesförarens dag"
["d0910"]="Internationella suicidpreventiva dagen"
["d0911"]="Kebabens dag"
["d0912"]="TV-spelsdagen
Europeiska migrändagen"
["d0914"]="Internationella dagen för atopiskt eksem"
["d0915"]="Internationella lymfomdagen"
["d0917"]="Höga klackars dag"
["d0918"]="E-bokens dag
Surkålens dag"
["d0919"]="Internationella piratdagen
Messmörets dag
Världsdagen för aortadissektion"
["d0920"]="Bålens dag
Allemansrättens dag"
["d0921"]="Internationella Alzheimerdagen
Minigolfdagen
Världstacksamhetsdagen
Scouternas fredsdag"
["d0922"]="Internationella bilfria dagen
Hobbitdagen
Noshörningens dag"
["d0923"]="Hjälpmedelsdagen
Bisexualitetens dag
Upphandlarens dag"
["d0924"]="Skiljetecknets dag
Dagvattnets dag"
["d0925"]="Äpplets dag
Internationella farmaceutdagen"
["d0926"]="Europeiska språkdagen"
["d0927"]="Tjänstepensionens dag"
["d0928"]="Internationella rabiesdagen
Neurodagen"
["d0929"]="Kaffets dag
Internationella hjärtdagen
Alla soffpotatisars dag
Återvinningens dag
Resandefolkets dag
Internationella pussdagen"
["d0930"]="International Blasphemy Rights Day
Naprapatins dag"
["d1001"]="Bröstcancerdagen
Vegetariska världsdagen
Svenska flaskans dag
Intelligensens dag"
["d1002"]="Lantbruksdjurens dag"
["d1003"]="Alla pojkvänners dag"
["d1004"]="Djurens dag
Internationella vodkadagen
Kanelbullens dag
Internationella Tacodagen"
["d1006"]="Nationella anhörigdagen
Internationella CP-dagen
HSP-dagen"
["d1007"]="Elmotorns dag"
["d1008"]="Vägledningens dag
Världsdyslexidagen"
["d1009"]="Minnesdag för avskaffandet av Sveriges transatlantiska slavhandel
PANDAS/PANS Awareness Day
Finlandssvenska matkulturdagen"
["d1010"]="Äggets dag
Grötens dag
Internationella dagen mot dödsstraff
Nordiska afasidagen"
["d1011"]="Äpplemustens Dag
Internationella komma-ut-dagen"
["d1012"]="Civilkuragets dag
Internationella reumatikerdagen
Sockerfria dagen"
["d1013"]="International Suit Up Day
Världstrombosdagen
Internationella klarspråksdagen
No Bra day"
["d1014"]="Räkmackans dag
Världsdagen för synskadade"
["d1015"]="Fetaostens dag
Internationella beröringsdagen
Internationella dagen för att tvätta händerna
Vita käppens dag
Brösthälsodagen
Metoo-dagen"
["d1016"]="Steve Jobs Day
Världslivsmedelsdagen
Lexikonens dag
Alla kan rädda liv-dagen
Världshungerdagen
Polyneuropatidagen"
["d1017"]="Parisarens dag"
["d1018"]="Internationella klimakteriedagen
Chokladmuffins dag
Alla broars dag
Internationella slipsdagen"
["d1019"]="Internationella gin och tonic-dagen
Nationella dagen för Strävhårig foxterrier"
["d1020"]="Internationella flygledardagen
Världsdagen för statistik
Internationella osteoporosdagen"
["d1022"]="INTERNATIONELLA CAPS LOCK-DAGEN
Internationella stamningsdagen"
["d1023"]="Internationella moldagen"
["d1024"]="Montessorilärardagen
Raggsockans dag
Snusets dag"
["d1025"]="Världspastadagen
Internationella Dysautonomi-dagen"
["d1026"]="Potatisens dag
Hjärnskadedagen"
["d1027"]="Arbetsterapins dag
Internationella nalledagen
Internationella religionsfrihetsdagen
Internationella skolbiblioteksdagen
Alla svärmödrars dag"
["d1028"]="Bilens dag
Internationella animationens dag
Veckopengens dag"
["d1029"]="Internationella psoriasisdagen
Internets dag"
["d1030"]="★ Dennis Ritchie-dagen ★"
["d1031"]="Grannens dag
Världsspardagen
Magins dag"
["d1101"]="Internationella vegandagen"
["d1104"]="No hate day"
["d1105"]="Guy Fawkes Day
Kaninköttets dag"
["d1106"]="Gustav Adolfsdagen"
["d1107"]="Kladdkakans dag"
["d1108"]="Infraservicedagen
Läromedlets dag
Röntgensjuksköterskans internationella yrkesdag"
["d1109"]="Internationella refluxdagen"
["d1111"]="Chokladens dag
Nordiska klimatdagen
Hågkomstens dag
Alla singlars dag
Hållbarhetsdagen för barn & unga"
["d1112"]="Alla krossade hjärtans dag
Miniatyrrävens dag
Globala lunginflammationsdagen"
["d1113"]="Smörgåstårtans dag"
["d1114"]="Ostkakans dag"
["d1115"]="Fängslade författares dag
Musikterapins dag
Filantropins dag"
["d1116"]="Mångkulturella matdagen"
["d1117"]="Internationella prematurdagen
Napoleonbakelsens dag
De prestigelösas dag
Internationella elevdagen"
["d1118"]="Adoptionernas dag
Europeiska antibiotikadagen
Benbuljongens dag"
["d1119"]="Internationella mansdagen
Världsdagen mot barnmisshandel
Internationella GIS-dagen
Amaryllisens dag
Internationella iktyosdagen
Womens Entrepreneurship Day"
["d1120"]="Minnesdag för transpersoner"
["d1121"]="Musikfri dag
Världshejardagen"
["d1122"]="Wienerbrödets dag"
["d1123"]="Internationella hattdagen"
["d1126"]="Internationella undersköterskedagen"
["d1127"]="Hudterapeutens dag"
["d1128"]="Flaskmatardagen"
["d1129"]="Vinylskivans dag"
["d1130"]="Guldsmedens dag
Kåldolmens dag"
["d1201"]="Brandvarnardagen
Glöggens dag"
["d1202"]="Modelljärnvägens dag"
["d1203"]="Drick en öl-dagen"
["d1204"]="Armbandsklockans dag"
["d1205"]="Internationella volontärdagen"
["d1209"]="Pepparkakans dag
Läkarsekreterarens dag"
["d1210"]="Internationella djurrättsdagen
Nobeldagen
Terra Madre day"
["d1211"]="Tangons dag"
["d1212"]="Julstjärnans dag"
["d1214"]="Internationella ap-dagen"
["d1218"]="Kakans dag"
["d1219"]="Jultröjans dag"
["d1221"]="Kortfilmens dag
Skumtomtens dag"
["d1223"]="Drottningens födelsedag"
["d1227"]="Nationella regifting-dagen"
["d1228"]="Värnlösa barns dag"
["d1229"]="Statisternas dag"
["d1231"]="Internationella Expect a better tomorrow-dagen"
)

today=${days[$day]}
if [[ ! -z ${today} ]]; then
    printf "%s\n" "$today"
fi

# Bkp:  Religiösa Helgdagar och dagar med rörliga datum - orka!
# 1 januari
# Nyårsdagen *
# 5 januari
# Trettondagsafton *
# 6 januari
# Trettondagen *
# 13 januari
# Tjugondag jul *
# 17 januari
# Internationella fetischdagen
# 18 januari
# Släktforskningens dag
# 19 januari
# Världsreligionsdagen
# Världssnödagen
# 26 januari
# Världsdagen för leprasjuka
# 1 februari
# Löpningens dag
# 10 februari
# Clean Out Your Computer Day
# 11 februari
# Safer internet day
# 14 februari
# Vintercyklingens dag
# 23 februari
# Kälkåkningens dag
# 1 mars
# Nolltaxedagen
# 2 mars
# Fastlagssöndagen
# 4 mars
# Fettisdagen
# 5 mars
# Askonsdagen
# 6 mars
# Fössta Tossdan i Mass
# 17 mars
# Saint Patrick's day *
# 22 mars
# Earth hour
# 12 april
# Surdegsdagen
# 13 april
# Såpbubblans dag
# 16 april
# Uniform på jobbet-dagen
# 17 april
# Knivens dag
# Skärtorsdagen
# 18 april
# Långfredagen
# 19 april
# Påskafton
# 20 april
# Påskdagen
# 21 april
# Annandag påsk
# 23 april
# Internationella sekreterardagen
# Sankt Georgsdagen *
# 26 april
# Den lokala handelns dag
# Alla barns dag
# 30 april
# Ledarhundens dag
# 2 maj
# Internationella tubadagen
# Byxfria dagen
# Grillens dag
# 3 maj
# Gratis serietidningsdagen
# Nakna trädgårdsdagen
# 4 maj
# Nässlans dag
# Världsskrattdagen
# Internationella barfotalöpningsdagen
# 10 maj
# Internationella dagen för rättvis handel
# Tunnbrödets dag
# Tunnbrödsrullens dag
# 11 maj
# Gosskörernas dag
# 13 maj
# Fritidshemmens dag
# Internationella strokedagen
# Skolidrottsföreningens dag
# 14 maj
# Gamla vänners dag
# 15 maj
# Förskolans dag
# 17 maj
# Internationella whiskydagen
# 21 maj
# IT-chefens dag
# Internationella flytvästdagen
# 24 maj
# Ofrivilligt barnlösas dag
# Mors dag
# 28 maj
# Kristi himmelsfärdsafton
# 29 maj
# Folknykterhetens dag
# Första metardagen
# Kristi himmelsfärdsdag
# Parfymfria dagen
# 7 juni
# Pingstafton
# Internationella brädspelsdagen
# Ångans dag
# 8 juni
# Pingstdagen
# 10 juni
# Ride to Work Day
# 14 juni
# Naturismens dag
# Världsstickningsdagen
# Husbilens dag
# Nationalbastudagen
# Mördarsnigelns otursdag
# 20 juni
# Midsommarafton
# 21 juni
# Internationella ALS-dagen
# Midsommardagen
# Sommarsolståndet
# 24 juni
# Johannes döparens dag *
# 30 juni
# Nationella entreprenörsdagen
# 5 juli
# Internationella dagen för kooperativ
# 9 juli
# Simborgarmärkets dag
# 10 juli
# Nationella orgasmdagen
# 16 juli
# Ölets dag
# 20 juli
# Skånska flaggans dag
# Baddräktsfria dagen
# 25 juli
# Systemadministratörens dag
# 1 augusti
# Internationella öldagen
# 2 augusti
# Örtens dag
# Senapens dag
# Hattens dag
# Ängens dag
# 3 augusti
# Hembygdsgårdarnas dag
# 7 augusti
# Internationella ipa-dagen
# 9 augusti
# Loppmarknadens dag
# 10 augusti
# Larsdagen *
# 16 augusti
# Hemlösa djurs dag
# Internationella geocachingdagen
# 21 augusti
# Surströmmingens dag
# 28 augusti
# Polisens dag
# Östersjödagen
# 30 augusti
# Squaredansens dag
# Koloniträdgårdens dag
# Snapsens dag
# 31 augusti
# Arkeologidagen
# Porslinets dag
# 1 september
# Labor day
# 6 september
# Ostronets dag
# Skäggets dag
# Hemslöjdens dag
# Scooterns dag
# 7 september
# Dansbandens dag
# Svampens dag
# Hittekattens dag
# 13 september
# Geologins dag
# Programmerarens dag
# Vandringens dag
# 14 september
# Kulturarvsdagen
# 20 september
# 4H-dagen
# Software freedom day
# Strandens dag
# Worldwide spin in public day
# Internationella röd panda-dagen
# Internationella Batman-dagen
# 21 september
# Brunchens dag
# 24 september
# Skolmjölkens dag
# 26 september
# Janssons-dagen
# 27 september
# Lösgodisets dag
# 3 oktober
# Alla pojkvänners dag *
# 5 oktober
# Den helige Mikaels dag
# Gräddtårtans dag
# 6 oktober
# Internationella dagen för boende- och bebyggelsefrågor
# Skolfotografiets dag
# 8 oktober
# Int. dagen för begränsning av naturkatastrofer
# 9 oktober
# Världssyndagen
# 10 oktober
# Äggets dag
# 11 oktober
# Musikens dag
# 12 oktober
# Tacksägelsedagen
# 14 oktober
# Ada Lovelace-dagen
# 16 oktober
# Grynkorvens dag
# Måltidens dag
# Alla chefers dag
# 18 oktober
# Alla broars dag
# 24 oktober
# Internationella champagnedagen
# 25 oktober
# Hackkorvens dag
# 1 november
# Alla helgons dag
# Allhelgonadagen *
# 2 november
# Alla själars dag
# 3 november
# Frysrättens dag
# 6 november
# Internationella stoutdagen
# 9 november
# Fars dag
# 10 november
# Mårtensafton *
# 13 november
# World Quality Day
# Användbarhetsdagen
# 16 november
# Världsdagen till minne av trafikoffer
# 18 november
# Raggmunkens dag
# 19 november
# Internationella KOL-dagen
# 20 november
# Världsfilosofidagen
# 23 november
# Sankt Clemens dag *
# 27 november
# Thanksgiving
# 28 november
# Pälsfria fredagen
# 30 november
# Andersdagen *
# 1 december
# Städarnas dag
# 6 december
# Nikolausdagen *
# 9 december
# Annadagen
# 12 december
# Tomasdagen
# 13 december
# Luciadagen *
# 19 december
# Jultröjans dag
# 24 december
# Julafton *
# 25 december
# Juldagen *
# 26 december
# Annandag jul *
# 31 december
# Nyårsafton *
