#!/bin/sh
# KESPLASH v1.46 - Simple Terminal Splash (for Arch Linux) Kjell Emanuelsson 2024

color_check=$(tput colors)
if [ $color_check -gt 254 ]; then
    LOW="\033[38;5;67m"
    MAIN="\033[38;5;111m"
    HI="\033[38;5;115m"
elif [ $color_check -gt 15 ]; then
    LOW="\e[34m"
    MAIN="\e[94m"
    HI="\e[92m"
else
    LOW="\e[39m"
    MAIN="\e[39m"
    HI="\e[39m"
fi

f_calctime () {
    printf '%dd %dh %dm' $(($1/86400)) $(($1%86400/3600)) $(($1%3600/60))
}

# Session Counter
count=$(printf "$(last reboot)" | grep -c '^')
count=$(($count-2))
today=$(date -u +%s)

# Extended Date + Time
now=$(LC_TIME="en_US.UTF-8"  date +'- %A %B %-d %Y, Week %-V, Q%-q - %H:%M %Z')

# System Up-time
up=$(uptime -p)

# System Life-time
paclog=$(sed -n "/ installed $1/{s/].*/]/p;q}" /var/log/pacman.log)
start_of_life=$(date -u -d ${paclog: 1:10} +%s)
life_s=$(($today - $start_of_life))
life=$(f_calctime $life_s)

# Theme OTD
un=$(day)
se=$(day-se)
daytxt=""

# annoying formatting
if [[ ! -z ${un} ]]; then
    daytxt=$(printf "${LOW}%s\n" "$un")
fi

if [[ ! -z ${se} ]]; then
    if [[ ! -z ${daytxt} ]]; then
        daytxt="${daytxt}$(printf "\n${MAIN}%s\n" "$se")"
    else
        daytxt=$(printf "${MAIN}%s\n" "$se")
    fi
fi

if [[ -z ${un} ]] && [[ -z ${se} ]]; then
    printf "\n${MAIN}[ Session #%i ] ${LOW}%s\n  (No observation/theme today!)\n${HI}  %s${LOW} - System life: %s \n\n" $count "$now" "$up" "$life"
else
    printf "\n${MAIN}[ Session #%i ] ${LOW}%s\n%s\n${HI}%s${LOW} - System life: %s \n\n" $count "$now" "$daytxt" "$up" "$life"
fi
